language: go
go:
- master
before_install:
- go get -t -v ./...
script:
- go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - master

before_deploy:
- git config --local user.name "YOUR GIT USER NAME"
- git config --local user.email "YOUR GIT USER EMAIL"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- go install

deploy:
  file: ${TRAVIS_HOME}/gopath/bin/travis-test
  provider: releases
  api_key:
    secure: mSwwmMA45CRdLlwg6AbadYdUyAc6k6UzPOQT1EVnI6dc8aPHqGEaCghFNvJHTj1WzHcr6LeNy5MWXr5Kugx61kLcuqnwQhJ5+suYbwTpeKVD4pbuslzJpyuiVvNl6QZfwO1edSFSsyWeqhnnoCBGBXbJ/ve6y1WS1+i1fbf6vjkGriXH6k1FotmKvOlfPX8RjnQwGT3MT7tEn+NXJHFNaiaoiMYw4hQZqzN6Q8cfROaW7em4h7nOSxUZ5cmazzpkVdkbR9t+7Zifdnl5UvptDjtgyWLA5hzB++vM8S8NpbNpmnnAoDGanFiwVGuZPXpwD1BRSGTxD/mCMAdSjY88QlM9xlTRIpSha3OCHWnM4n00FD3H52vobXI3fT0kkwmu0mps18gmk0Z2J74rfonDR7zDZwY0oV0IclWxXfpeSvjDxjDhOlu+lJDCFJ05VDMfRa+4JS2cvYWD+yXwHjDcw0BeyPf2uBXdy8vTKhfuyu2XzklobTwPz0mo7UvQ18eMp0MMEnIyq5QXrNCYUvKoE1jLLjaniBXMpHHOFPAka0vjhc/VDSuiLEohNhefBd5cWnTzNCemYzIF0GrtFPRu/69+QO5pASS/Idr+C2d6Mof3ngjZhPOuDMqWzxXbNJvlw/XVQxSVXYiqPc0HtOnesyhZHi0U5ZmyoSJcxKI2kLo=
  on:
    repo: wellington3110/travis-test
    branch: master
